DROP TABLE IF EXISTS p1_log;

create table if not exists p1_log (
   p1_id serial primary key,
   p1_timestamp timestamp(0) NOT NULL, 
   p1_meter_supplier character varying(4), 
   p1_header character varying(80),
   p1_dsmr_version character varying(2),
   p1_equipment_id character varying(50), 
   p1_meterreading_in_1 decimal(10,3), 
   p1_unitmeterreading_in_1 character varying(3), 
   p1_meterreading_in_2 decimal(10,3), 
   p1_unitmeterreading_in_2 character varying(3),
   p1_meterreading_out_1 decimal(10,3),
   p1_unitmeterreading_out_1 character varying(3),
   p1_meterreading_out_2 decimal(10,3),
   p1_unitmeterreading_out_2 character varying(3),
   p1_meterreading_prd decimal(10,3),
   p1_unitmeterreading_prd character varying(3),
   p1_current_tariff integer,
   p1_current_power_in decimal(10,3),
   p1_unit_current_power_in character varying(3),
   p1_current_power_out decimal(10,3),
   p1_unit_current_power_out character varying(3),
   p1_current_power_prd decimal(10,3),
   p1_unit_current_power_prd character varying(3),
   p1_current_threshold decimal(10,3),
   p1_unit_current_threshold character varying(3),
   p1_current_switch_position integer,
   p1_powerfailures integer,
   p1_long_powerfailures integer,
   p1_long_powerfailures_log character varying(1024),
   p1_voltage_sags_l1 integer,
   p1_voltage_sags_l2 integer,
   p1_voltage_sags_l3 integer,
   p1_voltage_swells_l1 integer,
   p1_voltage_swells_l2 integer,
   p1_voltage_swells_l3 integer,
   p1_instantaneous_current_l1 decimal(10,3),
   p1_unit_instantaneous_current_l1 character varying(3),
   p1_instantaneous_current_l2 decimal(10,3),
   p1_unit_instantaneous_current_l2 character varying(3),
   p1_instantaneous_current_l3 decimal(10,3),
   p1_unit_instantaneous_current_l3 character varying(3),
   p1_voltage_l1 decimal(10,3),
   p1_unit_voltage_l1 character varying(3),
   p1_voltage_l2 decimal(10,3),
   p1_unit_voltage_l2 character varying(3),
   p1_voltage_l3 decimal(10,3),
   p1_unit_voltage_l3 character varying(3),
   p1_instantaneous_active_power_in_l1 decimal(10,3),
   p1_unit_instantaneous_active_power_in_l1 character varying(3),
   p1_instantaneous_active_power_in_l2 decimal(10,3),
   p1_unit_instantaneous_active_power_in_l2 character varying(3),
   p1_instantaneous_active_power_in_l3 decimal(10,3),
   p1_unit_instantaneous_active_power_in_l3 character varying(3),
   p1_instantaneous_active_power_out_l1 decimal(10,3),
   p1_unit_instantaneous_active_power_out_l1 character varying(3),
   p1_instantaneous_active_power_out_l2 decimal(10,3),
   p1_unit_instantaneous_active_power_out_l2 character varying(3),
   p1_instantaneous_active_power_out_l3 decimal(10,3),
   p1_unit_instantaneous_active_power_out_l3 character varying(3),
   p1_message_code character varying(8),
   p1_message_text character varying(1024),
   p1_channel_1_id integer,
   p1_channel_1_type_id integer, 
   p1_channel_1_type_desc character varying(20),
   p1_channel_1_equipment_id character varying(50),
   p1_channel_1_timestamp timestamp(0),
   p1_channel_1_meterreading decimal(10,3), 
   p1_channel_1_unit character varying(3),
   p1_channel_1_valveposition integer,
   p1_channel_2_id integer,
   p1_channel_2_type_id integer, 
   p1_channel_2_type_desc character varying(20),
   p1_channel_2_equipment_id character varying(50),
   p1_channel_2_timestamp timestamp(0),
   p1_channel_2_meterreading decimal(10,3), 
   p1_channel_2_unit character varying(3),
   p1_channel_2_valveposition integer,
   p1_channel_3_id integer,
   p1_channel_3_type_id integer, 
   p1_channel_3_type_desc character varying(20),
   p1_channel_3_equipment_id character varying(50),
   p1_channel_3_timestamp timestamp(0),
   p1_channel_3_meterreading decimal(10,3), 
   p1_channel_3_unit character varying(3),
   p1_channel_3_valveposition integer,
   p1_channel_4_id integer,
   p1_channel_4_type_id integer, 
   p1_channel_4_type_desc character varying(20),
   p1_channel_4_equipment_id character varying(50),
   p1_channel_4_timestamp timestamp(0),
   p1_channel_4_meterreading decimal(10,3), 
   p1_channel_4_unit character varying(3),
   p1_channel_4_valveposition integer
);